apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odigos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://odigos-io.github.io/odigos
    chart: odigos
    targetRevision: 1.0.200
    helm:
      releaseName: odigos
      values: ""
        # OPTIONAL: add your custom Helm values here if needed.
        # Argo CD expects this field to be a YAML-formatted string.
        # To use chart defaults, delete this field entirely or set it to an empty string ("").
  destination:
    server: https://kubernetes.default.svc
    namespace: odigos-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true