apiVersion: batch/v1
kind: Job
metadata:
  name: delete-legacy-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking for legacy odigos-config ConfigMap..."
              if kubectl get configmap odigos-config -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                echo "Found. Deleting."
                kubectl delete configmap odigos-config -n {{ .Release.Namespace }}
              else
                echo "Not found. Skipping."
              fi
