apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: migration-role
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["odigos-config"]
  verbs: ["get","delete"]

