apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: migration-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
subjects:
- kind: ServiceAccount
  name: migration-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: migration-role
  apiGroup: rbac.authorization.k8s.io
