apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-role
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: 'true'
rules:
- apiGroups: [""]
  resources: ["namespaces", "configmaps"]
  verbs: ["get", "list", "patch", "delete"]