apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanup-clusterrole
  labels:
    odigos.io/system-object: "true"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list"]
- apiGroups: ["odigos.io"]
  resources: ["sources"]
  verbs: ["get", "list", "delete"]

