apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanup-clusterrole
  labels:
    odigos.io/system-object: "true"
rules:
- apiGroups: ["odigos.io"]
  resources: ["sources"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "delete"]

