apiVersion: v1
kind: ConfigMap
metadata:
  name: odigos-own-telemetry-otel-config
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/config: '1'
    odigos.io/system-object: 'true'
data:
  OTEL_SDK_DISABLED: "true"
