apiVersion: v1
kind: ConfigMap
metadata:
  name: odigos-config
  namespace: '{{ .Release.Namespace }}'
  annotations:
    'helm.sh/hook': post-install,post-upgrade
  labels:
    odigos.io/config: '1'
    odigos.io/system-object: 'true'
data:
  config.yaml: |
    configVersion: 1
    {{- if .Values.clusterName }}
    clusterName: {{ .Values.clusterName }}
    {{- end }}
    {{- if .Values.centralProxy.centralBackendURL }}
    centralBackendURL: {{ .Values.centralProxy.centralBackendURL }}
    {{- end }}
    imagePrefix: {{ template "utils.imagePrefix" (dict "Values" .Values) }}
    {{- if .Values.ui.uiMode }}
    uiMode: {{ .Values.ui.uiMode }}
    {{- end }}
    {{- if .Values.ui.uiPaginationLimit }}
    uiPaginationLimit: {{ .Values.ui.uiPaginationLimit }}
    {{- end }}
    {{- if include "odigos.shouldRenderUserInstrumentationEnvs" . | eq "true" }}
    userInstrumentationEnvs:
      languages:
        {{- range $lang, $config := .Values.userInstrumentationEnvs.languages }}
        {{- if or $config.enabled $config.env }}
        {{ $lang }}:
          enabled: {{ $config.enabled }}
          {{- if $config.env }}
          env:
            {{- range $key, $value := $config.env }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
    {{- end }}
    {{- if .Values.profiles }}
    profiles: 
      {{- toYaml .Values.profiles | nindent 6 }}
    {{- end }}
    telemetryEnabled: {{ .Values.telemetry.enabled }}
    openshiftEnabled: {{ .Values.openshift.enabled }}
    psp: {{ .Values.psp.enabled }}
    {{- if .Values.ignoredNamespaces }}
    ignoredNamespaces:
      {{- toYaml .Values.ignoredNamespaces | nindent 6 }}
    {{- end }}
    {{- if .Values.ignoredContainers }}
    ignoredContainers:
      {{- toYaml .Values.ignoredContainers | nindent 6 }}
    {{- end }}
    {{- if and .Values.instrumentor.mountMethod (has .Values.instrumentor.mountMethod (list "k8s-host-path" "k8s-virtual-device")) }}
    mountMethod: {{ .Values.instrumentor.mountMethod }}
    {{- else }}
    {{- fail "Error: Invalid mountMethod. Supported values are 'k8s-host-path' and 'k8s-virtual-device'." }}
    {{- end }}
    {{- if .Values.avoidInjectingJavaOptsEnvVar }}
    avoidInjectingJavaOptsEnvVar: {{ .Values.avoidInjectingJavaOptsEnvVar }}
    {{- end }}
    {{- if .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 6 }}
    {{- end }}
