apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP