# values-prometheus-agent.yaml
server:
  enabled: true
  extraArgs:
    enable-feature: agent
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.52.0
  persistentVolume:
    enabled: false
  retention: 0d

  serverFiles:
    prometheus.yml: |
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
        - job_name: 'node-exporter'
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              action: keep
              regex: monitoring
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              action: keep
              regex: prometheus-node-exporter
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              action: keep
              regex: (metrics|http-metrics)
        - job_name: 'kubernetes-pods'
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: "true"
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: (.+?)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
      remote_write:
        - url: "http://13.217.3.184:9090/api/v1/write"

alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: true
