server:
  enabled: true
  extraArgs:
    enable-feature: agent
  persistentVolume:
    enabled: false
  retention: null   # prevents Helm from setting --storage.tsdb.retention.time
  statefulSet:
    enabled: false  # avoids PV logic entirely
  remoteWrite:
    - url: "http://10.0.3.185:9090/api/v1/write"
  global:
    external_labels:
      cluster: "stress-tests-eks"
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: true
