apiVersion: actions.odigos.io/v1alpha1
kind: Action
metadata:
  name: label-attributes
  namespace: odigos-system
spec:
  signals:
    - LOGS
    - TRACES
  k8sAttributes:
    labels:
      - attributeKey: vm.app
        labelKey: vm.app
      - attributeKey: vm.env
        labelKey: vm.env
