apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odigos-instrumentor
  namespace: '{{ .Release.Namespace }}'
  labels:
    odigos.io/system-object: "true"
rules:
  - apiGroups:
      - ''
    resourceNames:
      - effective-config
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
# migration from the old odigos-config file - this can be removed once we are confident that the old config have been deleted
  - apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - odigos-config
    verbs:
      - get
      - delete
  - apiGroups:
      - odigos.io
    resources:
      - collectorsgroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - collectorsgroups/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - destinations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - instrumentationrules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - instrumentor-webhooks-cert
    verbs:
      - update
# migration from the old webhook cert - this can be removed once we are confident that the old secrets have been deleted
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - webhook-cert
    verbs:
      - delete
