apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-span-generator
  namespace: load-test
  labels:
    app: go-span-generator
    odigos-target: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-span-generator
      odigos-target: "true"
  template:
    metadata:
      labels:
        app: go-span-generator
        odigos-target: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: go-span-generator
          image: public.ecr.aws/odigos/go-span-gen:v0.0.1
          imagePullPolicy: Always
          env:
            - name: OTEL_SERVICE_NAME
              value: go-span-generator
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=go-span-generator,service.version=v1.0.0
            - name: SPANS_PER_SEC
              value: "1000"
            - name: SPAN_BYTES
              value: "1000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command:
                - pgrep
                - go-span-gen
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pgrep
                - go-span-gen
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-span-generator-service
  namespace: load-test
  labels:
    app: go-span-generator
spec:
  selector:
    app: go-span-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
