apiVersion: batch/v1
kind: Job
metadata:
  name: label-namespace
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: label-namespace
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - kubectl label namespace {{ .Release.Namespace }} odigos.io/system-object=true --overwrite
