apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-namespace
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-namespace-{{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-namespace-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-namespace-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: label-namespace
    namespace: {{ .Release.Namespace }}
