name: Trigger Odigos Enterprise Workflow

on:
  push:
    branches:
      - '**'
    paths:
      - 'github.com/odigos-io/odigos/common/**'
      - 'github.com/odigos-io/odigos/k8sUtils/**'
      - 'github.com/odigos-io/odigos/procdiscovery/**'
      - 'github.com/odigos-io/odigos/opamserver/**'
      - 'github.com/odigos-io/odigos/instrumentation/**'
      - 'github.com/odigos-io/ebpf-java-instrumentation/**'
      - 'github.com/odigos-io/ebpf-generic-instrumentation/**'
      - 'github.com/odigos-io/ebpf-nodejs-instrumentation/**'
jobs:
  trigger-odigos-enterprise:
    runs-on: ubuntu-latest
    steps:    
      - name: Trigger process PR in Odigos Enterprise
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_BOT_TOKEN }}" \
          https://api.github.com/repos/odigos-io/odigos-enterprise/dispatches \
          -d '{"event_type": "process_oss_pr", "client_payload": {"pr_creator": "${{ github.event.pull_request.user.login }}"}}'
